name: T2M-GPT
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.8  # CUDA 11.8 に対応するバージョン
  - cudatoolkit=11.8   # CUDA 依存関係を明示的に解決
  - numpy
  - pillow
  - ffmpeg
  - matplotlib=3.4.3
  - pandas
  - scikit-learn
  - scipy=1.7.1
  - tqdm
  - tensorboard
  - git  # ← `git clone` するなら必要
  - pip:
      - absl-py
      - charset-normalizer
      - chumpy
      - google-auth
      - google-auth-oauthlib
      - grpcio
      - imageio==2.9.0
      - ipython
      - joblib
      - markdown
      - matplotlib-inline
      - oauthlib
      - protobuf
      - requests
      - requests-oauthlib
      - rsa
      - smplx
      - tensorboard-plugin-wit
      - threadpoolctl
      - toml
      - urllib3
      - wcwidth
      - werkzeug
      - gdown
      - moviepy
      - git+https://github.com/openai/CLIP.git
      - git+https://github.com/nghorbani/human_body_prior
